### PR TITLE
Show icon delete the comment

### PR DESCRIPTION
**Pull request by nnthanhhuy**
Show icon delete the comment because of malformed HTML

### CODE REVIEW

**Comment by nikku** [comment]
The malformed HTML does not seem to be the source of the issue. At least I can see that your fix does not restore the actual delete handles (on Chrominum): 

image

How does the thing look for you, with your fixes applied?

**Comment by nnthanhhuy** [comment]
Thanks for the feedback. I checked it again and it works when I hover on it.
Screenshot (5)

**Comment by nikku** [comment]
My bad, I had an issue with the test CSS markup I used.

**Comment by nikku** [comment]
Thanks for your contribution. Good job :clap:

**Pull request merged**
